package acceltree.beans.model;

// Generated 26 Feb, 2016 12:22:10 PM by Hibernate Tools 3.4.0.CR1

/**
 * CreateDefect generated by hbm2java
 */
public class CreateDefect implements java.io.Serializable {

	private Integer defecId;
	private String defectNo;
	private String comment;

	public CreateDefect() {
	}

	public CreateDefect(String defectNo, String comment) {
		this.defectNo = defectNo;
		this.comment = comment;
	}

	public Integer getDefecId() {
		return this.defecId;
	}

	public void setDefecId(Integer defecId) {
		this.defecId = defecId;
	}

	public String getDefectNo() {
		return this.defectNo;
	}

	public void setDefectNo(String defectNo) {
		this.defectNo = defectNo;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
