package acceltree.beans.model;

// Generated 26 Feb, 2016 12:22:10 PM by Hibernate Tools 3.4.0.CR1

/**
 * Defectstatus generated by hbm2java
 */
public class Defectstatus implements java.io.Serializable {

	private Integer defectStatusId;
	private String statusType;

	public Defectstatus() {
	}

	public Defectstatus(String statusType) {
		this.statusType = statusType;
	}

	public Integer getDefectStatusId() {
		return this.defectStatusId;
	}

	public void setDefectStatusId(Integer defectStatusId) {
		this.defectStatusId = defectStatusId;
	}

	public String getStatusType() {
		return this.statusType;
	}

	public void setStatusType(String statusType) {
		this.statusType = statusType;
	}

}
