package acceltree.beans.model;

// Generated 26 Feb, 2016 12:22:10 PM by Hibernate Tools 3.4.0.CR1

/**
 * DefectCategory generated by hbm2java
 */
public class DefectCategory implements java.io.Serializable {

	private Integer defCategoryId;
	private String defectCategoryName;

	public DefectCategory() {
	}

	public DefectCategory(String defectCategoryName) {
		this.defectCategoryName = defectCategoryName;
	}

	public Integer getDefCategoryId() {
		return this.defCategoryId;
	}

	public void setDefCategoryId(Integer defCategoryId) {
		this.defCategoryId = defCategoryId;
	}

	public String getDefectCategoryName() {
		return this.defectCategoryName;
	}

	public void setDefectCategoryName(String defectCategoryName) {
		this.defectCategoryName = defectCategoryName;
	}

}
