package acceltree.beans.model;

// Generated 26 Feb, 2016 12:22:10 PM by Hibernate Tools 3.4.0.CR1

/**
 * IssuedType generated by hbm2java
 */
public class IssuedType implements java.io.Serializable {

	private Integer idIssuedType;
	private String issuedName;

	public IssuedType() {
	}

	public IssuedType(String issuedName) {
		this.issuedName = issuedName;
	}

	public Integer getIdIssuedType() {
		return this.idIssuedType;
	}

	public void setIdIssuedType(Integer idIssuedType) {
		this.idIssuedType = idIssuedType;
	}

	public String getIssuedName() {
		return this.issuedName;
	}

	public void setIssuedName(String issuedName) {
		this.issuedName = issuedName;
	}

}
