package acceltree.beans.model;

// Generated 26 Feb, 2016 12:22:10 PM by Hibernate Tools 3.4.0.CR1

/**
 * Usermaster generated by hbm2java
 */
public class Usermaster implements java.io.Serializable {

	private Integer idusermaster;
	private String usertype;

	public Usermaster() {
	}

	public Usermaster(String usertype) {
		this.usertype = usertype;
	}

	public Integer getIdusermaster() {
		return this.idusermaster;
	}

	public void setIdusermaster(Integer idusermaster) {
		this.idusermaster = idusermaster;
	}

	public String getUsertype() {
		return this.usertype;
	}

	public void setUsertype(String usertype) {
		this.usertype = usertype;
	}

}
